from turtle import *

def flowerdraw(fillcolor = fillcolor("orange")):
    pencolor("brown")
    pensize(2.5)
    fillcolor
    begin_fill()
    lt(60)
    fd(80)
    lt(60)
    fd(80)
    lt(60)
    fd(80)
    lt(60)
    fd(80)
    lt(60)
    fd(80)
    lt(60)
    fd(80)
    end_fill()

def flowerdraw2(fillcolor = fillcolor("orange")):
    pencolor("brown")
    pensize(2.5)
    fillcolor
    begin_fill()
    rt(60)
    fd(80)
    rt(60)
    fd(80)
    rt(60)
    fd(80)
    rt(60)
    fd(80)
    rt(60)
    fd(80)
    rt(60)
    fd(80)
    end_fill()

def flower(flowerdraw, flowerdraw2):
    pu()
    fd(69)
    lt(90)
    fd(40)
    pd()
    flowerdraw(fillcolor("gold"))
    end_fill()
    pu()
    home()
    # Erstes Sechseck
    pu()
    lt(90)
    fd(160)
    pd()
    flowerdraw(fillcolor("orange"))
    pu()
    home()
    # Zweites Sechseck
    pu()
    lt(180)
    fd(69)
    rt(90)
    fd(40)
    pd()
    flowerdraw(fillcolor("orange"))
    pu()
    home()
    # Drittes Sechseck
    pu()
    rt(90)
    fd(160)
    pd()
    flowerdraw2()
    pu()
    home()
    # Viertes Sechseck
    pu()
    rt(90)
    fd(160)
    pd()
    flowerdraw(fillcolor("orange"))
    pu()
    home()
    # Fuenftes Sechseck
    pu()
    fd(69)
    lt(90)
    fd(40)
    pd()
    flowerdraw2()
    pu()
    home()
    # Sechstes Sechseck
    pu()
    lt(90)
    fd(160)
    pd()
    flowerdraw2()
    pu()
    home()
    # Siebtes Sechseck
    pu()
    fd(34.5)
    lt(90)
    fd(20)
    pd()
    a = 1
    while (a == 1):
        pd()
        pencolor("brown")
        pensize(2.5)
        fillcolor("orange")
        fillcolor
        begin_fill()
        lt(60)
        fd(40)
        lt(60)
        fd(40)
        lt(60)
        fd(40)
        lt(60)
        fd(40)
        lt(60)
        fd(40)
        lt(60)
        fd(40)
        end_fill()
        pu()
    # Kleines Sechseck
flower(flowerdraw, flowerdraw2)